# Form implementation generated from reading ui file 'GestionBodega.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(795, 468)
        self.lblnombreBod = QtWidgets.QLabel(parent=Dialog)
        self.lblnombreBod.setGeometry(QtCore.QRect(31, 31, 43, 16))
        self.lblnombreBod.setObjectName("lblnombreBod")
        self.txtNombreBod = QtWidgets.QLineEdit(parent=Dialog)
        self.txtNombreBod.setGeometry(QtCore.QRect(80, 31, 116, 20))
        self.txtNombreBod.setObjectName("txtNombreBod")
        self.txtTipoBod = QtWidgets.QLineEdit(parent=Dialog)
        self.txtTipoBod.setGeometry(QtCore.QRect(307, 31, 116, 20))
        self.txtTipoBod.setObjectName("txtTipoBod")
        self.lblTipo = QtWidgets.QLabel(parent=Dialog)
        self.lblTipo.setGeometry(QtCore.QRect(276, 31, 25, 16))
        self.lblTipo.setObjectName("lblTipo")
        self.txtUbicacion = QtWidgets.QLineEdit(parent=Dialog)
        self.txtUbicacion.setGeometry(QtCore.QRect(560, 31, 116, 20))
        self.txtUbicacion.setObjectName("txtUbicacion")
        self.lblUbicacion = QtWidgets.QLabel(parent=Dialog)
        self.lblUbicacion.setGeometry(QtCore.QRect(503, 31, 51, 16))
        self.lblUbicacion.setObjectName("lblUbicacion")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 110, 481, 201))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lblDescripcionbod = QtWidgets.QLabel(parent=Dialog)
        self.lblDescripcionbod.setGeometry(QtCore.QRect(30, 90, 60, 16))
        self.lblDescripcionbod.setObjectName("lblDescripcionbod")
        self.btnAgregarBod = QtWidgets.QPushButton(parent=Dialog)
        self.btnAgregarBod.setGeometry(QtCore.QRect(80, 380, 75, 23))
        self.btnAgregarBod.setObjectName("btnAgregarBod")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblnombreBod.setText(_translate("Dialog", "Nombre:"))
        self.lblTipo.setText(_translate("Dialog", "Tipo:"))
        self.lblUbicacion.setText(_translate("Dialog", "Ubicacion:"))
        self.lblDescripcionbod.setText(_translate("Dialog", "Descripcion:"))
        self.btnAgregarBod.setText(_translate("Dialog", "Agregar"))
